### ISSUE TITLE
Insecure use of /tmp

### ISSUE THREAD

**Issue by plobbes** [Zimbra-Community/zimbra-tools#3]
We should change this to use mktemp to create temp files safely.

`cat <<EOF > /tmp/policyd-install.sql
`

Ref: https://github.com/Zimbra-Community/zimbra-tools/blob/master/cbpolicyd.sh#L49

**Comment by ghost** [comment]
Thanks, I fixed the script so it generated files like below for each run:

ls /tmp -w1
cbpolicyd.conf.in.n5wJftOt
policyd-dbcreate.Dzol3vD5.sql
policyd-dbtables.Ks8hVamQ.sql
policyd-policy.AyZfcVl4.sql
