### ISSUE TITLE
zimbra.service set type to forking

### ISSUE THREAD

**Issue by floek** [Zimbra-Community/zimbra-tools#4]
Hi,
I had to set ```Type=forking``` in ```/etc/systemd/system/zimbra.service``` to prevent systemd from stopping the service everytime.

I also had some Issues with amavis and dependend perl libs. I had to set
```Environment=PERL5LIB=/opt/zimbra/common/lib/perl5/x86_64-linux-gnu-thread-multi:/opt/zimbra/common/lib/perl5```

Maybe you can verify this.

Greetings

Floek

**Comment by ghost** [comment]
I have not used this in a while, since the rc init stuff still works
on CentOS7.

Can you send a PR so we can merge the changes? Thanks!
