### ISSUE TITLE
How to import Zimbra to Outlook PST?

### ISSUE THREAD

**Issue by priyaruby86** [Zimbra-Community/zimbra-tools#7]
My friend asked me a query about import Zimbra tgz to Outlook pst, so I search tool from google, then I got tool from this site:

[http://www.recoverymails.com/zimbra-to-outlook.html](http://www.recoverymails.com/zimbra-to-outlook.html)

so I was tried it, but it is paid tool. so I want to know to any free solution tool to resolve the issues.

**Comment by ghost** [comment]
Please check https://forums.zimbra.org/
